name: mashecho
favicon: null
layout_spectrum: 0.12263684161007404
typography_spectrum: 0.29506093775853515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9511928865686059
  lightness: 0.985197457484901
  saturation: 0.12407719274051487
  rhythmicContrast: 0.23897896381095052
purpose: []
